config/routes.rb
require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  root to: "posts#index"

  get "/about", to: "pages#about"
  get "/pdx-food", to: "pages#pdx_food"

  # For the generic /posts/:id route (i.e. to route to a post without using
  # its type, like Article or Note), we'll only support numeric IDs. Only
  # polymorphic routes will support something like fetching posts by slugs.
  # This also ensures that our legacy URLs listed below won't conflict.
  get "/posts/:id", to: "posts#show", as: :post, constraints: {id: /\d+/}

  resources :posts, only: [:index, :create, :edit, :update, :destroy]
  resources :articles, only: [:index, :show]
  resources :check_ins, only: [:index, :show], path: "check-ins"
  resources :links, only: [:index, :show]
  resources :notes, only: [:index, :show]
  resources :photos, only: [:index]
  resources :hashtags, only: [:show]

  resources :feeds, only: [:index]
  get "/rss", to: "feeds#index"

  get "/feeds/all", to: "feeds#all", format: :xml, as: :all_feed
  get "/feeds/articles", to: "feeds#articles", format: :xml, as: :articles_feed
  get "/feeds/check-ins", to: "feeds#check_ins", format: :xml, as: :check_ins_feed
  get "/feeds/links", to: "feeds#links", format: :xml, as: :links_feed
  get "/feeds/notes", to: "feeds#notes", format: :xml, as: :notes_feed
  get "/feeds/photos", to: "feeds#photos", format: :xml, as: :photos_feed
  get "/feeds/main", to: "feeds#main", format: :xml, as: :main_feed
  get "/feed", to: "feeds#main", format: :xml

  post :webmention, to: "webmentions#receive"

  # Set up routes for me to authenticate and write/edit posts.
  namespace :github do
    namespace :oauth do
      get :callback
    end
  end

  # Route media attachments through a CDN.
  direct :cdn_file do |file|
    if Rails.configuration.cdn_host.present?
      File.join(Rails.configuration.cdn_host, file.key)
    else
      route_for(:rails_blob, file)
    end
  end

  post :direct_uploads, to: "direct_uploads#create", as: :direct_uploads

  constraints(AdminConstraint.new) do
    mount Sidekiq::Web => "/admin/sidekiq"
  end

  get :sign_in, to: "sessions#new"
  delete :sign_out, to: "sessions#destroy"
  get "/mapkit/token", to: "sessions#mapkit_token"

  # Finally, ensure old URLs redirect to the new location for existing articles
  get "/blog/2012/02/01/why-i-hate-five-star-ratings", to: redirect("/articles/why-i-hate-five-star-ratings/")
  get "/blog/2012/02/07/collaborative-filtering-with-likes-and-dislikes", to: redirect("/articles/collaborative-filtering-with-likes-and-dislikes/")
  get "/blog/2012/07/18/the-current-state-of-rails-inflections", to: redirect("/articles/the-state-of-rails-inflections/")
  get "/blog/2012/07/31/edge-rails-a-multilingual-inflector", to: redirect("/articles/internationalization-and-the-rails-inflector/")
  get "/blog/2012/09/06/stop-validating-email-addresses-with-regex", to: redirect("/articles/stop-validating-email-addresses-with-regex/")
  get "/blog/2013/03/20/the-story-of-my-redis-database", to: redirect("/articles/from-1-5-gb-to-50-mb-the-story-of-my-redis-database/")
  get "/blog/2013/05/02/deploying-discourse-with-capistrano", to: redirect("/articles/deploying-discourse-with-capistrano/")
  get "/blog/2015/01/29/distance-constraints-with-postgresql-and-postgis", to: redirect("/articles/distance-constraints-with-postgresql-and-postgis/")

  get "/posts/why-i-hate-five-star-ratings", to: redirect("/articles/why-i-hate-five-star-ratings/")
  get "/posts/collaborative-filtering-with-likes-and-dislikes", to: redirect("/articles/collaborative-filtering-with-likes-and-dislikes/")
  get "/posts/the-current-state-of-rails-inflections", to: redirect("/articles/the-state-of-rails-inflections/")
  get "/posts/edge-rails-a-multilingual-inflector", to: redirect("/articles/internationalization-and-the-rails-inflector/")
  get "/posts/stop-validating-email-addresses-with-regex", to: redirect("/articles/stop-validating-email-addresses-with-regex/")
  get "/posts/the-story-of-my-redis-database", to: redirect("/articles/from-1-5-gb-to-50-mb-debugging-memory-usage-in-redis/")
  get "/posts/deploying-discourse-with-capistrano", to: redirect("/articles/deploying-discourse-with-capistrano/")
  get "/posts/distance-constraints-with-postgresql-and-postgis", to: redirect("/articles/distance-constraints-with-postgresql-and-postgis/")
  get "/posts/publish-your-site-to-s3", to: redirect("/articles/easily-publish-your-site-to-s3-and-cloudfront/")
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_proper_content_type, except: :index
  after_action :track_page_view

  def index
  end

  def main
    _, @posts = pagy(Post.main.includes(Post::FEED_INCLUDES))

    # For check-ins, we'll preload their places and snapshots
    ActiveRecord::Associations::Preloader.new(
      records: @posts.select(&:check_in?),
      associations: CheckIn::DEFAULT_INCLUDES + [{snapshot_attachment: :blob}]
    ).call

    @self_url = main_feed_url
    @alternate_url = root_url

    render :feed, formats: :xml
  end

  def all
    _, @posts = pagy(Post.includes(Post::FEED_INCLUDES))

    # For check-ins, we'll preload their places and snapshots
    ActiveRecord::Associations::Preloader.new(
      records: @posts.select(&:check_in?),
      associations: CheckIn::DEFAULT_INCLUDES + [{snapshot_attachment: :blob}]
    ).call

    @subtitle = "Everything"
    @self_url = all_feed_url
    @alternate_url = root_url

    render :feed, formats: :xml
  end

  def articles
    _, @posts = pagy(Article.includes(Post::FEED_INCLUDES))

    @subtitle = "Articles"
    @self_url = articles_feed_url
    @alternate_url = articles_url

    render :feed, formats: :xml
  end

  def check_ins
    _, @posts = pagy(CheckIn.includes(Post::FEED_INCLUDES + CheckIn::DEFAULT_INCLUDES + [{snapshot_attachment: :blob}]))

    @subtitle = "Check-ins"
    @self_url = check_ins_feed_url
    @alternate_url = check_ins_url

    render :feed, formats: :xml
  end

  def links
    _, @posts = pagy(Link.includes(Post::FEED_INCLUDES))

    @subtitle = "Links"
    @self_url = links_feed_url
    @alternate_url = links_url

    render :feed, formats: :xml
  end

  def notes
    _, @posts = pagy(Note.includes(Post::FEED_INCLUDES))

    @subtitle = "Notes"
    @self_url = notes_feed_url
    @alternate_url = notes_url

    render :feed, formats: :xml
  end

  def photos
    posts = Post.includes(Post::FEED_INCLUDES)
      .joins(:media_attachments)
      .where(media_attachments: {featured: true})

    _, @posts = pagy(posts)

    @subtitle = "Photos"
    @self_url = photos_feed_url
    @alternate_url = photos_url

    render :feed, formats: :xml
  end

  private

  def set_proper_content_type
    response.headers.delete "X-Content-Type-Options"
    response.headers["Content-Type"] = "text/xml; charset=utf-8"
  end
end

app/views/feeds/index.html.erb
<div class="py-8">
  <div class="lg:px-8">
    <div class="lg:max-w-4xl">
      <div class="mx-auto px-4 sm:px-6 md:max-w-2xl md:px-4 lg:px-0">
        <h1 class="text-2xl font-bold leading-7 text-slate-900">RSS Feeds</h1>
      </div>
    </div>
  </div>

  <div class="sm:mt-4 lg:mt-8 lg:border-t lg:border-slate-100">
    <article class="py-10 sm:py-12">
      <div class="lg:px-8">
        <div class="lg:max-w-4xl">
          <div class="mx-auto px-4 sm:px-6 md:max-w-2xl md:px-4 lg:px-0">
            <div class="prose prose-slate mt-1 text-base leading-7 text-slate-700 lg:prose-lg prose-ul:pl-0 prose-li:pl-0 prose-a:text-pink-500 hover:prose-a:text-pink-700 active:prose-a:text-pink-900">
              <p>
                Still using a feed reader? Me too! I rely on RSS feeds to keep up
                with other blogs and news sites, so I make sure to provide them
                for my own content as well. Every post I write is syndicated via
                RSS, and I maintain multiple feeds so you can pick and choose from
                whatever you’re interested in:
              </p>

              <p>
                The <%= link_to "main feed", main_feed_path %> has my core posts:
                <%= link_to "articles", articles_path %>, <%= link_to "notes", notes_path %>,
                and <%= link_to "links", links_path %> that I share. Check-ins will also
                appear, but only when I had something to say or included a picture. You can
                also subscribe to each kind of post individually:
              </p>

              <ul class="list-none">
                <li>
                  <span class="select-none">📝</span>

                  The <%= link_to "articles feed", articles_feed_path %> contains only
                  my long-form <%= link_to "articles", articles_path %>. I write these
                  pretty infrequently, so you won't get too many updates here.
                </li>

                <li>
                  <span class="select-none">✏️</span>

                  The <%= link_to "notes feed", notes_feed_path %> just has my short-form
                  <%= link_to "notes", notes_path %> (aka "tweets" or "lukewarm takes").
                  These are more frequent, but not as much as when I was on Twitter.
                </li>

                <li>
                  <span class="select-none">🔗</span>

                  The <%= link_to "links feed", links_feed_path %> tracks the
                  <%= link_to "links", links_path %> that I share from around the web
                  with a bit of commentary from me. Unlike the other feeds, clicking on
                  the title of a link in your feed reader will take you to the source
                  material instead of my site. If you want to get to my site, you can
                  click on the little 🍕 at the bottom of the entry in your reader.
                </li>

                <li>
                  <span class="select-none">📍</span>

                  The <%= link_to "check-ins feed", check_ins_feed_path %> contains <em>all</em>
                  of my <%= link_to "check-ins", check_ins_path %>. I sometimes check in a lot,
                  and you probably won’t really care when I do. But if you do want to see where
                  I’m hanging out or what I’m up to, feel free!
                </li>

                <li>
                  <span class="select-none">📸</span>

                  The <%= link_to "photos feed", photos_feed_path %> has the
                  <%= link_to "photos", photos_path %> that I take and feature on my site.
                  I share pics in different ways, so you’ll see a mix of mostly notes and
                  check-ins in this feed.
                </li>

                <li>
                  <span class="select-none">🗃️</span>

                  I also have one <%= link_to "mega feed", all_feed_path %> that’ll get you
                  everything I post. I can’t in good conscience recommend it, but it’s there.
                </li>
              </ul>

              <h3 id="how-to-subscribe">How to Subscribe</h3>

              <p>
                If you’re new to RSS, you’ll need an RSS reader. There are a lot of options
                out there but, if you’re in the Apple ecosystem like me, I highly recommend
                <a href="https://reederapp.com/">Reeder</a>. It’s available for macOS, iOS,
                and iPadOS, and you can subscribe to feeds right from the app and have them
                sync across all of your devices via iCloud.
              </p>

              <p>
                Once you have an RSS reader, you can subscribe to any of the feeds above
                by clicking on their links; that should prompt you to open them in whatever
                reader you’ve installed. If that doesn’t work and they open in your browser
                instead, you can copy the URL and paste it into whatever your reader app’s
                “new subscription” flow is. Thanks for reading!
              </p>
            </div>
          </div>
        </div>
      </div>
    </article>
  </div>
</div>

<%= content_for(:og_title, "@davidcelis’s RSS Feeds") %>
<%= content_for(:og_description, "Read my posts in your preferred feed reader!") %>
<%= content_for(:og_type, "profile") %>