config/routes.rb
require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  root to: "posts#index"

  get "/about", to: "pages#about"
  get "/pdx-food", to: "pages#pdx_food"

  # For the generic /posts/:id route (i.e. to route to a post without using
  # its type, like Article or Note), we'll only support numeric IDs. Only
  # polymorphic routes will support something like fetching posts by slugs.
  # This also ensures that our legacy URLs listed below won't conflict.
  get "/posts/:id", to: "posts#show", as: :post, constraints: {id: /\d+/}

  resources :posts, only: [:index, :create, :edit, :update, :destroy]
  resources :articles, only: [:index, :show]
  resources :check_ins, only: [:index, :show], path: "check-ins"
  resources :links, only: [:index, :show]
  resources :notes, only: [:index, :show]
  resources :photos, only: [:index]
  resources :hashtags, only: [:show]

  resources :feeds, only: [:index]
  get "/rss", to: "feeds#index"

  get "/feeds/all", to: "feeds#all", format: :xml, as: :all_feed
  get "/feeds/articles", to: "feeds#articles", format: :xml, as: :articles_feed
  get "/feeds/check-ins", to: "feeds#check_ins", format: :xml, as: :check_ins_feed
  get "/feeds/links", to: "feeds#links", format: :xml, as: :links_feed
  get "/feeds/notes", to: "feeds#notes", format: :xml, as: :notes_feed
  get "/feeds/photos", to: "feeds#photos", format: :xml, as: :photos_feed
  get "/feeds/main", to: "feeds#main", format: :xml, as: :main_feed
  get "/feed", to: "feeds#main", format: :xml

  post :webmention, to: "webmentions#receive"

  # Set up routes for me to authenticate and write/edit posts.
  namespace :github do
    namespace :oauth do
      get :callback
    end
  end

  # Route media attachments through a CDN.
  direct :cdn_file do |file|
    if Rails.configuration.cdn_host.present?
      File.join(Rails.configuration.cdn_host, file.key)
    else
      route_for(:rails_blob, file)
    end
  end

  post :direct_uploads, to: "direct_uploads#create", as: :direct_uploads

  constraints(AdminConstraint.new) do
    mount Sidekiq::Web => "/admin/sidekiq"
  end

  get :sign_in, to: "sessions#new"
  delete :sign_out, to: "sessions#destroy"
  get "/mapkit/token", to: "sessions#mapkit_token"

  # Finally, ensure old URLs redirect to the new location for existing articles
  get "/blog/2012/02/01/why-i-hate-five-star-ratings", to: redirect("/articles/why-i-hate-five-star-ratings/")
  get "/blog/2012/02/07/collaborative-filtering-with-likes-and-dislikes", to: redirect("/articles/collaborative-filtering-with-likes-and-dislikes/")
  get "/blog/2012/07/18/the-current-state-of-rails-inflections", to: redirect("/articles/the-state-of-rails-inflections/")
  get "/blog/2012/07/31/edge-rails-a-multilingual-inflector", to: redirect("/articles/internationalization-and-the-rails-inflector/")
  get "/blog/2012/09/06/stop-validating-email-addresses-with-regex", to: redirect("/articles/stop-validating-email-addresses-with-regex/")
  get "/blog/2013/03/20/the-story-of-my-redis-database", to: redirect("/articles/from-1-5-gb-to-50-mb-the-story-of-my-redis-database/")
  get "/blog/2013/05/02/deploying-discourse-with-capistrano", to: redirect("/articles/deploying-discourse-with-capistrano/")
  get "/blog/2015/01/29/distance-constraints-with-postgresql-and-postgis", to: redirect("/articles/distance-constraints-with-postgresql-and-postgis/")

  get "/posts/why-i-hate-five-star-ratings", to: redirect("/articles/why-i-hate-five-star-ratings/")
  get "/posts/collaborative-filtering-with-likes-and-dislikes", to: redirect("/articles/collaborative-filtering-with-likes-and-dislikes/")
  get "/posts/the-current-state-of-rails-inflections", to: redirect("/articles/the-state-of-rails-inflections/")
  get "/posts/edge-rails-a-multilingual-inflector", to: redirect("/articles/internationalization-and-the-rails-inflector/")
  get "/posts/stop-validating-email-addresses-with-regex", to: redirect("/articles/stop-validating-email-addresses-with-regex/")
  get "/posts/the-story-of-my-redis-database", to: redirect("/articles/from-1-5-gb-to-50-mb-debugging-memory-usage-in-redis/")
  get "/posts/deploying-discourse-with-capistrano", to: redirect("/articles/deploying-discourse-with-capistrano/")
  get "/posts/distance-constraints-with-postgresql-and-postgis", to: redirect("/articles/distance-constraints-with-postgresql-and-postgis/")
  get "/posts/publish-your-site-to-s3", to: redirect("/articles/easily-publish-your-site-to-s3-and-cloudfront/")
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_authentication, only: [:create, :edit, :update]

  def index
    posts = Post.includes(Post::DEFAULT_INCLUDES)
    posts = posts.unscope(:order).search(params[:q]) if params[:q].present?
    @pagy, @posts = pagy(posts)

    ActiveRecord::Precounter.new(@posts).precount(:likes, :reposts, :replies)

    # For check-ins, we'll preload their associated places.
    ActiveRecord::Associations::Preloader.new(
      records: @posts.select(&:check_in?),
      associations: CheckIn::DEFAULT_INCLUDES
    ).call

    # For link previews, we'll preload their favicons and preview images.
    ActiveRecord::Associations::Preloader.new(
      records: @posts.select(&:link?),
      associations: Link::DEFAULT_INCLUDES
    ).call

    respond_to :html
  end

  def show
    @post = Post.includes(Post::DEFAULT_INCLUDES).find(params[:id])

    instance_variable_set(:"@#{@post.type.underscore}", @post)

    render "#{@post.type.tableize}/show", formats: [:html]
  end

  def create
    # If the post is being created with any media attachments, we'll push the
    # post creation into a background job. This lets us handle the processing
    # of the media attachments without hogging a web worker and also ensures
    # we can wait to create the Post object until the media is done processing.
    # This includes check-ins (they generate an Apple Maps snapshot) as well as
    # links (they store cached versions of the link's relevant images like open
    # graph images and a favicons).
    if media_attachments_params.any? || place_params.key?(:apple_maps_id) || post_params[:type] == "Link"
      CreatePostWithMediaJob.perform_async(post_params.to_hash, media_attachments_params.map(&:to_hash), place_params.to_hash)

      redirect_to root_path, notice: "Your post’s media is being processed and will be available shortly."
      return
    end

    @post = Post.new(post_params)

    # Use the WeatherKit API to get the weather for the post's location.
    begin
      aqi = AQI.at(latitude: @post.latitude, longitude: @post.longitude)
      @post.weather = {"airQualityIndex" => aqi}

      response = Apple::WeatherKit::CurrentWeather.at(latitude: @post.latitude, longitude: @post.longitude)
      @post.weather.merge!(response["currentWeather"])
    rescue Faraday::Error
      # Occasionally, Apple's WeatherKit API just starts returning 401s for no
      # reason. These have always been transient, but it typically takes a few
      # hours before resolving itself. To avoid preventing myself from posting
      # for long stretches of time, I just enqueue a job to bring the weather
      # data in later, and the job can retry until it works.
    end

    # If we don't have a check-in, we'll still find or create a generic Place
    # for the post's location.
    @post.place = Place.find_or_create_by(place_params) if place_params.present?

    if @post.save
      AddWeatherToPostJob.perform_async(@post.id) unless @post.has_weather_data?

      redirect_to polymorphic_path(@post)
    else
      render :index, alert: @post.errors.full_messages.to_sentence
    end
  end

  def edit
    @post = Post.includes(Post::DEFAULT_INCLUDES).find(params[:id])
  end

  def update
    post = Post.find(params[:id])

    ActiveRecord::Base.transaction do
      # We only support updating the post's title, content, and media
      post_params = params.require(:post).permit(:title, :content)
      post.update!(post_params)

      # Destroy any media attachments that weren't re-submitted in the update
      post.media_attachments.where.not(id: media_attachments_params.map { |p| p[:id] }).destroy_all

      # Update or create the media attachments that _were_ submitted
      media_attachments_params.each do |media_attachment_params|
        media_attachment = if media_attachment_params[:id].present?
          post.media_attachments.find(media_attachment_params[:id])
        elsif media_attachment_params[:signed_id].present?
          post.media_attachments.new(file: media_attachment_params[:signed_id])
        end

        media_attachment.update!(media_attachment_params.slice(:description, :featured))
      end
    end

    redirect_to polymorphic_path(post), notice: "Post updated!"
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy!

    redirect_to root_path, notice: "Post deleted!"
  end

  private

  def post_params
    params.require(:post).permit(:type, :title, :content, :latitude, :longitude, :link_data).tap do |p|
      p.delete(:title) unless %(Article Link).include?(p[:type])

      p[:link_data] = JSON.parse(p[:link_data]) if p[:type] == "Link"
    end
  end

  def media_attachments_params
    params.require(:post).permit(media_attachments: [:id, :signed_id, :description, :featured]).fetch(:media_attachments, [])
  end

  def place_params
    params.require(:post).permit(place: %i[
      name
      category
      street
      city
      state
      state_code
      postal_code
      country
      country_code
      latitude
      longitude
      apple_maps_id
      apple_maps_url
    ]).fetch(:place, {}).compact_blank
  end
end

app/helpers/post_helper.rb
module PostHelper
  EMOJI = {
    "Article" => "📝",
    "Note" => "✏️",
    "Link" => "🔗",
    "CheckIn" => "📍"
  }.freeze

  def post_emoji(post)
    EMOJI[post.type]
  end
end

app/views/posts/_complications.html.erb
<div class="flex flex-col flex-wrap justify-between space-y-1 w-full pt-4 text-sm text-slate-500">
  <span data-controller="local-time" data-local-time-full-value class="font-mono">
    <span class="font-sans select-none" data-local-time-target="emoji" aria-hidden="true"><%= clock_emoji(post.created_at) %> </span>

    <%= link_to polymorphic_path(post), class: "u-url text-sm font-bold leading-6 link-primary" do %>
      <%= timestamp(post.created_at, full: true, classes: ["dt-published"]) %>
    <% end %>
  </span>

  <% if post.place.present? %>
    <span class="font-mono text-slate-500">
      <span class="font-sans select-none" aria-hidden="true">📍 </span>
      <%= link_to "#{post.place.name}", post.place.apple_maps_url, class: "link-primary font-bold" %>
      <span>/ <%= post.place.city_state_and_country(separator: " / ") %></span>
    </span>

    <% if post.has_weather_data? %>
      <span class="font-mono text-slate-500 flex">
        <span class="font-sans select-none" aria-hidden="true"><%= weather_emoji(post) %>&nbsp;</span>
        <span><%= (post.weather["temperatureApparent"] * 1.8 + 32).round %>°F <%= weather_conditions(post) %></span>
        <% if (aqi = post.weather["airQualityIndex"]) %>
          <span>&nbsp;(AQI <%= aqi %></span>
          <span class="flex flex-col justify-center items-center ml-2 select-none"><span class="h-2 w-2 rounded-full <%= aqi_bg_color(aqi) %>"></span></span>
          <span>)</span>
        <% end %>
      </span>
    <% end %>

    <% post.syndication_links.sort_by(&:platform).each do |link| %>
      <% webmentions = post.webmentions.select { |webmention| webmention.platform == link.platform } %>

      <span class="font-mono text-slate-500">
        <%= syndication_link_tag(link, webmentions: webmentions) %>
      </span>
    <% end %>
  <% end %>

  <% if authenticated? %>
    <span class="font-mono">
      <span class="font-sans select-none" aria-hidden="true">🔏 </span>
      <%= link_to "Edit post", edit_post_path(post.id), class: "link-primary font-bold" %>
    </span>

    <span class="font-mono">
      <span class="font-sans select-none" aria-hidden="true">🚮 </span>
      <%= link_to "Delete post", post_path(post.id), class: "link-primary font-bold", data: { turbo_method: :delete, turbo_confirm: "You sure?" } %>
    </span>
  <% end %>
</div>

app/views/posts/_list.html.erb
<div class="h-feed py-12 sm:py-8">
  <div class="lg:px-8">
    <div class="lg:max-w-4xl">
      <div class="flex justify-between mx-auto px-4 sm:px-6 md:max-w-2xl md:px-4 lg:px-0">
        <h1 class="p-name text-2xl font-bold leading-7 text-slate-900 lg:pt-2">
          <%= link_to header, request.path, class: "u-url" %>
        </h1>

        <% search_url = posts_url unless params[:controller].in?(["posts", "articles", "check_ins", "links", "notes", "hashtags"]) %>

        <form id="search" class="hidden lg:block relative w-48" data-controller="search" data-search-url-value="<%= search_url %>" data-action="search#submit:prevent">
          <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center">
            <span class="text-center h-6 w-6 ml-1 pl-1">🔎</span>
          </div>

          <input type="text" data-action="input->search#toggleClear" data-search-target="query" value="<%= params[:q] %>" class="w-full pl-8 pr-7 border border-slate-300 rounded-md shadow-sm focus:ring-pink-500 focus:border-pink-500 block sm:text-sm" placeholder="<%= search_placeholder %>" aria-label="Search" />

          <div class="absolute inset-y-0 right-0 flex items-center">
            <button type="button" data-search-target="clear" data-action="search#clear" class="h-6 w-6 mr-1<%= " hidden" unless params[:q] %>" aria-label="Clear search" title="Clear search">
              ❌
            </button>
          </div>

          <input type="submit" class="hidden" />
        </form>
      </div>
    </div>
  </div>

  <div class="sm:mt-4 lg:mt-8 lg:border-t lg:border-slate-100">
    <% if authenticated? && params[:controller] == "posts" && @pagy.page == 1 %>
      <%= render "posts/form" %>
    <% end %>

    <section class="divide-y divide-slate-100">
      <%= render @posts %>

      <% if @posts.empty? %>
        <div class="py-10 sm:py-12">
          <div class="lg:px-8">
            <div class="lg:max-w-4xl">
              <div class="mx-auto px-4 sm:px-6 md:max-w-2xl md:px-4 lg:px-0">
                <div class="flex flex-col items-start">
                  <section class="prose prose-slate prose-a:text-pink-500 hover:prose-a:text-pink-700 active:prose-a:text-pink-900 mt-1 text-base leading-7 text-slate-700 lg:prose-lg">
                    <span class="select-none md:absolute md:-ml-6 mr-2" title="Search" aria-hidden="true">
                      🔎
                    </span>

                    <span>No results found.</span>
                  </section>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>

      <% if @pagy.pages > 1 %>
        <%= render "pagination" %>
      <% end %>
    </section>
  </div>
</div>

app/views/posts/_meta.html.erb
<% index ||= false %>

<% if index %>
  <div data-controller="local-time" class="mt-4 flex items-center gap-2 font-mono text-sm text-slate-500">
    <%= link_to polymorphic_path(post), class: "u-url flex items-center text-sm font-bold leading-6 link-primary" do %>
      <span class="font-sans select-none md:absolute md:-ml-6 mr-2" title="<%= post.humanized_type %>" aria-hidden="true">
        <%= post_emoji(post) %>
      </span>

      <%= timestamp(post.created_at, classes: ["dt-published"]) %>
    <% end %>

    <% if post.replies_count > 0 %>
      <span class="select-none" aria-hidden="true">/ </span>
      <span title="Replies" aria-label="Replies">💬 <%= post.replies_count %></span>
    <% end %>

    <% if post.reposts_count > 0 %>
      <span class="select-none" aria-hidden="true">/ </span>
      <span title="Reposts" aria-label="Reposts">🔁 <%= post.reposts_count %></span>
    <% end %>

    <% if post.likes_count > 0 %>
      <span class="select-none" aria-hidden="true">/ </span>
      <span title="Likes" aria-label="Likes"><span class="font-sans">❤️</span> <%= post.likes_count %></span>
    <% end %>
  </div>
<% else %>
  <div class="e-content prose prose-slate prose-a:text-pink-500 hover:prose-a:text-pink-700 active:prose-a:text-pink-900 mt-4 pb-4 text-base leading-7 text-slate-700 lg:prose-lg border-y border-slate-200">
    <p class="pt-4 text-sm">
      Did you like this post, repost it, or respond to it? Let me know by sending a

      <%= link_to "webmention", about_path(anchor: "webmentions"), target: "_blank" %>!
    </p>

    <%= form_tag webmention_path, class: "relative flex" do %>
      <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center">
        <span class="text-center ml-1 pl-1">🌐</span>
      </div>

      <%= text_field_tag :source, nil, class: "grow mr-4 pl-9 pr-7 border border-slate-300 rounded-md shadow-sm focus:ring-pink-500 focus:border-pink-500 block sm:text-sm", placeholder: "https://example.com/your-post" %>
      <%= hidden_field_tag :target, polymorphic_url(post) %>
      <%= hidden_field_tag :manual, true %>

      <%= button_tag "@ me", type: "submit", class: "inline-flex items-center gap-2 justify-center rounded-md py-2 px-3 text-sm outline-offset-2 transition active:transition-none bg-slate-100 font-medium hover:bg-pink-100 active:bg-slate-100 active:text-pink-900/60 link-primary group" %>
    <% end%>
  </div>

  <% if (likes = post.webmentions.select(&:like?).reject(&:from_bridgy?).presence) %>
    <%= render partial: "posts/likes", locals: {likes: likes} %>
  <% end %>

  <% if (reposts = post.webmentions.select(&:repost?).reject(&:from_bridgy?).presence) %>
    <%= render partial: "posts/reposts", locals: {reposts: reposts} %>
  <% end %>

  <% if (replies = post.webmentions.select(&:reply?).reject(&:from_bridgy?).presence) %>
    <%= render partial: "posts/replies", locals: {replies: replies.sort_by(&:published_at)} %>
  <% end %>
<% end %>

<div class="hidden">
  <div class="u-author h-card">
    <%= image_tag "me.jpg", alt: "A sketch of a bearded man with long, curly hair from the side, seated with his hands clasped in his lap while wearing light shorts, a black shirt, black sneakers, and a black baseball cap as a thought bubble expands from his head containing a slice of pepperoni pizza.", class: "u-photo" %>
    <%= link_to "David Celis", root_path, class: "p-name u-url" %>
  </div>

  <% if post.updated_at != post.created_at %>
    <%= timestamp(post.updated_at, full: true, classes: ["dt-updated"]) %>
  <% end %>

  <% if post.is_a?(CheckIn) %>
    <div class="p-geo">
      <span class="p-latitude"><%= post.place.latitude %></span>
      <span class="p-longitude"><%= post.place.longitude %></span>
    </div>
  <% end %>

  <% post.syndication_links.each do |link| %>
    <%= link_to link.platform, link.url, class: "u-syndication" %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<% content_for :head do %>
  <%# Prevent Turbo from caching the page; it doesn't play nicely with the form. %>
  <meta name="turbo-cache-control" content="no-cache">
<% end %>

<div class="py-12 sm:py-8">
  <div class="sm:mt-4 lg:mt-8 lg:border-t lg:border-slate-100">
    <section id="post-form" class="py-10 sm:py-12 border-b border-slate-100">
      <div class="lg:px-8">
        <div class="lg:max-w-4xl">
          <div class="mx-auto px-4 sm:px-6 md:max-w-2xl md:px-4 lg:px-0">
            <div class="flex">
              <%= form_with model: @post, url: post_path(@post.id), html: {class: "relative grow", data: {"controller" => "post-editor", "post-editor-target" => "form", "post-editor-direct-upload-url-value" => direct_uploads_url}} do |f| %>
                <div class="post-editor-container border border-slate-300 rounded-lg shadow-sm overflow-hidden">
                  <%= hidden_field_tag "_type", @post.type, data: {"post-editor-target" => "type"} %>

                  <%= f.text_field :title, name: "post[title]", placeholder: "Title", class: "#{"hidden " unless @post.title.present?}block w-full border-0 pt-2.5 text-lg font-medium placeholder-slate-500 focus:ring-0", data: {"post-editor-target" => "title"} %>
                  <%= f.text_area :content, name: "post[content]", data: {"post-editor-target" => "editor"} %>

                  <div aria-hidden="true">
                    <div class="flex flex-wrap px-2 gap-x-2" data-post-editor-target="mediaPreviewZone">
                      <% @post.media_attachments.each do |media| %>
                        <div class="relative w-32 h-32 mb-2" data-post-editor-target="mediaPreview" data-controller="reveal" data-file-name="<%= media.filename %>" data-file-size="<%= media.byte_size %>" data-file-type="<%= media.content_type %>" data-file-last-modified="<%= media.updated_at.to_i %>">
                          <% if media.image? %>
                            <%= image_tag cdn_file_url(media), class: "object-cover rounded height-full w-full shadow-md" %>
                          <% elsif media.video_or_gif? %>
                            <%= image_tag cdn_file_url(media.preview_image), class: "object-cover rounded height-full w-full shadow-md" %>
                          <% end %>

                          <%= hidden_field_tag "post[media_attachments][][id]", media.id %>
                          <%= hidden_field_tag "post[media_attachments][][signed_id]", nil %>

                          <button class="absolute bottom-1 left-1 px-1 font-bold font-ui-sans rounded-[.25rem] bg-black bg-opacity-[.65] hover:bg-black text-white select-none" data-action="click->reveal#show:prevent" data-reveal-target="button">+ALT</button>

                          <div class="hidden" data-reveal-target="item">
                            <div class="fixed inset-0 z-[25] height-screen w-screen bg-slate-800/40 backdrop-blur-sm opacity-100" data-action="click->reveal#hide:prevent"></div>
                            <div class="fixed top-8 max-h-[92vh] inset-x-4 mx-auto z-[50] origin-top flex flex-col gap-4 p-4 rounded-md max-w-prose bg-white opacity-100 scale-100 overflow-y-auto" data-reveal-target="item">
                              <div class="flex justify-between">
                                <h2 class="text-xl font-bolt text-slate-900">Description</h2>
                                <button class="text-sm py-0 px-2 rounded-sm transition active:transition-none bg-slate-100 font-medium hover:bg-pink-100 active:bg-slate-100 active:text-pink-900/60 link-primary" data-action="click->reveal#hide:prevent">Close</button>
                              </div>

                              <% if media.image? %>
                                <%= image_tag cdn_file_url(media), class: "object-cover rounded height-full w-full shadow-md" %>
                              <% elsif media.video_or_gif? %>
                                <%= image_tag cdn_file_url(media.preview_image), class: "object-cover rounded height-full w-full shadow-md" %>
                              <% end %>

                              <%= text_area_tag "post[media_attachments][][description]", media.description, placeholder: "Describe the image", class: "border border-slate-200 rounded p-2 text-slate-900 focus:outline-none focus:ring-2 focus:ring-pink-500 focus:border-transparent placeholder:italic min-h-[100px] resize-none", data: {"reveal-target" => "focus"} %>

                              <div class="flex items-center">
                                <button data-action="click->post-editor#toggleFeaturedMedia:prevent type="button" role="switch" class="<%= media.featured? ? "bg-pink-600" : "bg-slate-200" %> relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus:ring-2 focus:ring-indigo-600 focus:ring-offset-2">
                                  <span class="<%= media.featured? ? "translate-x-5" : "translate-x-0" %> pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out"></span>
                                </button>

                                <span class="ml-3 text-sm text-slate-900">Featured</span>

                                <%= hidden_field_tag "post[media_attachments][][featured]", media.featured? %>
                              </div>

                              <button class="p-2 mt-2 w-full rounded-sm transition active:transition-none bg-slate-100 font-medium hover:bg-pink-100 active:bg-slate-100 active:text-pink-900/60 link-primary" data-action="click->reveal#hide:prevent">Confirm</button>
                            </div>
                          </div>

                          <button class="absolute top-1 right-1 p-1 rounded-full bg-black bg-opacity-[.65] hover:bg-black" data-action="click->post-editor#removeMediaAttachment:prevent">
                            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 fill-white" viewBox="0 0 320 512"><path d="M310.6 150.6c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0L160 210.7 54.6 105.4c-12.5-12.5-32.8-12.5-45.3 0s-12.5 32.8 0 45.3L114.7 256 9.4 361.4c-12.5 12.5-12.5 32.8 0 45.3s32.8 12.5 45.3 0L160 301.3 265.4 406.6c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L205.3 256 310.6 150.6z"></path></svg>
                          </button>
                        </div>
                      <% end %>
                    </div>

                    <div class="border-t border-slate-200 px-2 py-2 flex justify-between items-center space-x-3 sm:px-3">
                      <div class="flex-shrink">
                        <div class="flex justify-between items-center space-x-3">
                          <button type="button" class="group flex items-center" data-action="click->post-editor#selectFiles">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" class="h-8 w-8 fill-slate-400 group-hover:fill-slate-600"><path d="M220.6 121.2L271.1 96 448 96v96H333.2c-21.9-15.1-48.5-24-77.2-24s-55.2 8.9-77.2 24H64V128H192c9.9 0 19.7-2.3 28.6-6.8zM0 128V416c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V96c0-35.3-28.7-64-64-64H271.1c-9.9 0-19.7 2.3-28.6 6.8L192 64H160V48c0-8.8-7.2-16-16-16H80c-8.8 0-16 7.2-16 16l0 16C28.7 64 0 92.7 0 128zM168 304a88 88 0 1 1 176 0 88 88 0 1 1 -176 0z"/></svg>
                            <span class="hidden">Attach media</span>
                          </button>

                          <%= file_field_tag :files, multiple: true, hidden: true, accept: "image/*,video/*", data: {"post-editor-target" => "dummyFileField", "action" => "change->post-editor#dummyFileFieldChanged"} %>
                        </div>
                      </div>

                      <div class="flex-shrink-0">
                        <span id="character_counter" class="select-none text-sm text-slate-500 italic px-2" data-post-editor-target="characterCounter">500</span>
                        <button type="submit" class="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-pink-500 hover:bg-pink-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-pink-500">Update</button>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </section>

    <style>
      /* Ink MDE customization */
      .ink-mde {
        border: none !important;

        --ink-code-font-family: 'Fira Code', Consolas, Monaco, 'Andale Mono', 'Ubuntu Mono', monospace;
        --ink-font-family: var(--ink-code-font-family);

        /* Figure out how to keep the carat from disappearing in dark mode */
      }

      .ink-mde-editor {
        min-height: 144px !important;
        cursor: text;
      }

      .cm-focused {
        outline: none !important;
      }
    </style>

  </div>
</div>