config/routes.rb
require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  root to: "posts#index"

  get "/about", to: "pages#about"
  get "/pdx-food", to: "pages#pdx_food"

  # For the generic /posts/:id route (i.e. to route to a post without using
  # its type, like Article or Note), we'll only support numeric IDs. Only
  # polymorphic routes will support something like fetching posts by slugs.
  # This also ensures that our legacy URLs listed below won't conflict.
  get "/posts/:id", to: "posts#show", as: :post, constraints: {id: /\d+/}

  resources :posts, only: [:index, :create, :edit, :update, :destroy]
  resources :articles, only: [:index, :show]
  resources :check_ins, only: [:index, :show], path: "check-ins"
  resources :links, only: [:index, :show]
  resources :notes, only: [:index, :show]
  resources :photos, only: [:index]
  resources :hashtags, only: [:show]

  resources :feeds, only: [:index]
  get "/rss", to: "feeds#index"

  get "/feeds/all", to: "feeds#all", format: :xml, as: :all_feed
  get "/feeds/articles", to: "feeds#articles", format: :xml, as: :articles_feed
  get "/feeds/check-ins", to: "feeds#check_ins", format: :xml, as: :check_ins_feed
  get "/feeds/links", to: "feeds#links", format: :xml, as: :links_feed
  get "/feeds/notes", to: "feeds#notes", format: :xml, as: :notes_feed
  get "/feeds/photos", to: "feeds#photos", format: :xml, as: :photos_feed
  get "/feeds/main", to: "feeds#main", format: :xml, as: :main_feed
  get "/feed", to: "feeds#main", format: :xml

  post :webmention, to: "webmentions#receive"

  # Set up routes for me to authenticate and write/edit posts.
  namespace :github do
    namespace :oauth do
      get :callback
    end
  end

  # Route media attachments through a CDN.
  direct :cdn_file do |file|
    if Rails.configuration.cdn_host.present?
      File.join(Rails.configuration.cdn_host, file.key)
    else
      route_for(:rails_blob, file)
    end
  end

  post :direct_uploads, to: "direct_uploads#create", as: :direct_uploads

  constraints(AdminConstraint.new) do
    mount Sidekiq::Web => "/admin/sidekiq"
  end

  get :sign_in, to: "sessions#new"
  delete :sign_out, to: "sessions#destroy"
  get "/mapkit/token", to: "sessions#mapkit_token"

  # Finally, ensure old URLs redirect to the new location for existing articles
  get "/blog/2012/02/01/why-i-hate-five-star-ratings", to: redirect("/articles/why-i-hate-five-star-ratings/")
  get "/blog/2012/02/07/collaborative-filtering-with-likes-and-dislikes", to: redirect("/articles/collaborative-filtering-with-likes-and-dislikes/")
  get "/blog/2012/07/18/the-current-state-of-rails-inflections", to: redirect("/articles/the-state-of-rails-inflections/")
  get "/blog/2012/07/31/edge-rails-a-multilingual-inflector", to: redirect("/articles/internationalization-and-the-rails-inflector/")
  get "/blog/2012/09/06/stop-validating-email-addresses-with-regex", to: redirect("/articles/stop-validating-email-addresses-with-regex/")
  get "/blog/2013/03/20/the-story-of-my-redis-database", to: redirect("/articles/from-1-5-gb-to-50-mb-the-story-of-my-redis-database/")
  get "/blog/2013/05/02/deploying-discourse-with-capistrano", to: redirect("/articles/deploying-discourse-with-capistrano/")
  get "/blog/2015/01/29/distance-constraints-with-postgresql-and-postgis", to: redirect("/articles/distance-constraints-with-postgresql-and-postgis/")

  get "/posts/why-i-hate-five-star-ratings", to: redirect("/articles/why-i-hate-five-star-ratings/")
  get "/posts/collaborative-filtering-with-likes-and-dislikes", to: redirect("/articles/collaborative-filtering-with-likes-and-dislikes/")
  get "/posts/the-current-state-of-rails-inflections", to: redirect("/articles/the-state-of-rails-inflections/")
  get "/posts/edge-rails-a-multilingual-inflector", to: redirect("/articles/internationalization-and-the-rails-inflector/")
  get "/posts/stop-validating-email-addresses-with-regex", to: redirect("/articles/stop-validating-email-addresses-with-regex/")
  get "/posts/the-story-of-my-redis-database", to: redirect("/articles/from-1-5-gb-to-50-mb-debugging-memory-usage-in-redis/")
  get "/posts/deploying-discourse-with-capistrano", to: redirect("/articles/deploying-discourse-with-capistrano/")
  get "/posts/distance-constraints-with-postgresql-and-postgis", to: redirect("/articles/distance-constraints-with-postgresql-and-postgis/")
  get "/posts/publish-your-site-to-s3", to: redirect("/articles/easily-publish-your-site-to-s3-and-cloudfront/")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  rescue_from Pagy::VariableError do |e|
    @exception = Errors::BadRequest.new(e.message, original_exception: e)

    render "errors/bad_request", status: @exception.status_code
  end

  def authenticated?
    cookies.encrypted[:github_user_id] == Rails.application.credentials.dig(:github, :user_id)
  end
  helper_method :authenticated?

  def require_authentication
    redirect_to root_path unless authenticated?
  end

  def track_page_view
    plausible_client.event(
      name: "pageview",
      url: request.original_url,
      user_agent: request.user_agent,
      referrer: request.referrer,
      ip: request.remote_ip
    )
  rescue => e
    # Don't let Plausible errors break the app, but let me know
    Sentry.capture_exception(e)
  end
  helper_method :track_page_view

  private

  def plausible_client
    @client ||= if Rails.env.production?
      PlausibleApi::Client.new
    else
      NullPlausibleClient.new
    end
  end

  class NullPlausibleClient
    def event(*)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/application/_flash.html.erb
<% flash.each do |type, message| %>
  <div
    data-controller="notification"
    data-notification-delay-value="5000"
    data-transition-enter-from="opacity-0 translate-x-6"
    data-transition-enter-to="opacity-100 translate-x-0"
    data-transition-leave-from="opacity-100 translate-x-0"
    data-transition-leave-to="opacity-0 translate-x-6"
    class="transition transform duration-1000 hidden absolute top-0 right-0 m-2 z-[9999]"
  >
    <div class="flex flex-col gap-4 p-4 max-w-prose bg-white rounded-md border-slate-200 border-1 shadow-md">
      <div class="flex justify-between">
        <h2 class="text-xl font-bold text-slate-900"><%= type.titleize %></h2>

        <button class="text-sm py-0 px-2 ml-2 rounded-sm transition active:transition-none bg-slate-100 font-medium hover:bg-pink-100 active:bg-slate-100 active:text-pink-900/60 link-primary" data-action="notification#hide">Dismiss</button>
      </div>

      <p class="whitespace-pre-wrap text-base text-slate-700"><%= message %></p>
    </div>
  </div>
<% end %>

app/views/application/_footer.html.erb
<footer class="flex flex-col border-t border-slate-200 bg-slate-50 pt-10 sm:pt-16 lg:hidden">
  <div class="mx-auto px-4 sm:px-6 md:max-w-2xl md:px-4">
    <section>
      <h2 class="flex items-center font-mono text-sm font-medium leading-7 text-slate-900">
        <svg aria-hidden="true" viewBox="0 0 10 10" class="h-2.5 w-2.5">
          <path d="M0 5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V5Z" class="fill-violet-300"></path>
          <path d="M6 1a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V1Z" class="fill-pink-300"></path>
        </svg>
        <span class="ml-2.5">About me</span>
      </h2>

      <p class="mt-2 text-base leading-7 text-slate-700">
        Hey there, I’m David! I’m a Senior Staff Engineer working on
        <a href="https://firehydrant.com/" class="link-primary" target="_blank">FireHydrant</a>
        (where I write APIs) out in Portland, Ore. (where I drink IPAs). I write about tech
        (rarely), <%= link_to "food", pdx_food_path, class: "link-primary" %> (often), and whatever else is on my mind.
      </p>
    </section>

    <section>
      <h2 class="mt-8 flex items-center font-mono text-sm font-medium leading-7 text-slate-900">
        <svg aria-hidden="true" viewBox="0 0 10 10" class="h-2.5 w-2.5">
          <path d="M0 5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V5Z" class="fill-indigo-300"></path>
          <path d="M6 1a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V1Z" class="fill-blue-300"></path>
        </svg>
        <span class="ml-2.5">Work</span>
      </h2>

      <%= render "work" %>
    </section>

    <section class="pb-40 sm:pb-32">
      <h2 class="mt-8 flex items-center font-mono text-sm font-medium leading-7 text-slate-900">
        <svg aria-hidden="true" viewBox="0 0 10 10" class="h-2.5 w-2.5">
          <path d="M0 5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V5Z" class="fill-fuchsia-300"></path>
          <path d="M6 1a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V1Z" class="fill-purple-300"></path>
        </svg>
        <span class="ml-2.5">Follow me</span>
      </h2>

      <%= render "social_links", class: "mt-4 flex justify-center gap-10 text-base font-medium leading-7 text-slate-700 sm:gap-8" %>
    </section>

    <section class="pb-4 sm:pb-2">
      <p class="text-center text-slate-500">\ No newline at end of file</p>
    </section>
  </div>
</footer>

app/views/application/_header.html.erb
<header class="h-card bg-slate-50 lg:fixed lg:inset-y-0 lg:left-0 lg:flex lg:w-96 lg:items-start lg:overflow-y-auto lg:overscroll-contain xl:w-[26rem]">
  <div class="relative mx-auto px-4 pb-4 pt-10 sm:px-6 md:max-w-2xl md:px-4 lg:min-h-full lg:flex-auto lg:border-x lg:border-slate-200 lg:py-12 lg:px-8 xl:px-12">
    <%= link_to root_path, class: "relative mx-auto block w-24 overflow-hidden rounded-lg bg-slate-200 shadow-xl shadow-slate-200 z-10 sm:rounded-xl lg:w-auto lg:rounded-2xl", aria: {label: "homepage"} do %>
      <%= image_tag "me.jpg", width: 960, height: 960, class: "u-photo w-full hidden lg:block", alt: "A sketch of a bearded man with long, curly hair wearing a baseball cap, seated with his hands clasped in his lap as a thought bubble expands from his head with a slice of pepperoni pizza."%>
      <%= image_tag "my-face.jpg", width: 960, height: 960, class: "u-photo w-full block lg:hidden", alt: "A sketch of a bearded man with long, curly hair wearing a baseball cap."%>

      <div class="absolute inset-0 rounded-lg ring-1 ring-inset ring-black/10 sm:rounded-xl lg:rounded-2xl"></div>
    <% end %>

    <div class="mt-10 text-center lg:mt-12 lg:text-left">
      <p class="text-xl font-bold text-slate-900">
        <%= link_to "David Celis", root_path, class: "p-name u-url" %>
      </p>

      <p class="mt-3 text-lg font-medium leading-8 text-slate-500">
        Amateur pizzaiolo and engineer.
      </p>
    </div>

    <section class="mt-12 hidden lg:block">
      <h2 class="flex items-center font-mono text-sm font-medium leading-7 text-slate-900">
        <svg aria-hidden="true" viewBox="0 0 10 10" class="h-2.5 w-2.5">
          <path d="M0 5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V5Z" class="fill-violet-300"></path>
          <path d="M6 1a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V1Z" class="fill-pink-300"></path>
        </svg>
        <span class="ml-2.5">About me</span>
      </h2>

      <p class="p-note mt-2 text-base leading-7 text-slate-700">
        Hey there, I’m David! I’m a <span class= "p-job-title">Senior Staff Engineer</span> working on
        <a href="https://firehydrant.com/" class="p-org link-primary" target="_blank">FireHydrant</a>
        (where I write APIs) out in <span class="p-locality">Portland</span>, <span class="p-region">Ore.</span>
        (where I drink IPAs). I write about tech (rarely), <%= link_to "food", pdx_food_path, class: "link-primary" %> (often), and whatever else is on my mind.
      </p>
    </section>

    <section class="mt-12 hidden lg:block">
      <h2 class="flex items-center font-mono text-sm font-medium leading-7 text-slate-900">
        <svg aria-hidden="true" viewBox="0 0 10 10" class="h-2.5 w-2.5">
          <path d="M0 5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V5Z" class="fill-indigo-300"></path>
          <path d="M6 1a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V1Z" class="fill-blue-300"></path>
        </svg>
        <span class="ml-2.5">Work</span>
      </h2>

      <%= render "work" %>
    </section>

    <section class="max-lg:hidden mt-10 lg:mt-12">
      <h2 class="sr-only flex items-center font-mono text-sm font-medium leading-7 text-slate-900 lg:not-sr-only">
        <svg aria-hidden="true" viewBox="0 0 10 10" class="h-2.5 w-2.5">
          <path d="M0 5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V5Z" class="fill-fuchsia-300"></path>
          <path d="M6 1a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V1Z" class="fill-purple-300"></path>
        </svg>
        <span class="ml-2.5">Follow me</span>
      </h2>

      <div class="h-[1px] bg-gradient-to-r from-slate-200/0 via-slate-200 to-slate-200/0 lg:hidden"></div>

      <%= render "social_links", class: "mt-4 flex justify-center gap-10 text-base font-medium leading-7 text-slate-700 sm:gap-8 lg:flex-col lg:gap-4" %>
    </section>
  </div>
</header>

app/views/application/_navigation.html.erb
<div class="max-lg:absolute max-lg:top-0 max-lg:right-0 max-w-7xl lg:px-8">
  <div class="lg:max-w-4xl">
    <div class="relative p-4">
      <div class="mx-auto lg:max-w-2xl xl:max-w-5xl">
        <div class="relative flex justify-center">
          <div data-controller="reveal" data-action="keydown.esc@window->reveal#hide" class="pointer-events-auto lg:hidden">
            <button data-action="click->reveal#show keydown.esc@window->reveal#hide" data-reveal-target="button" type="button" aria-expanded="false" aria-controls="nav-popup" aria-haspopup="menu" class="group flex items-center rounded-full bg-white/90 px-4 py-2 text-sm font-medium text-slate-800 shadow-lg shadow-slate-800/5 ring-1 ring-slate-900/5 backdrop-blur">
              Menu
              <svg viewBox="0 0 8 6" aria-hidden="true" class="ml-3 height-auto w-2 stroke-slate-500 group-hover:stroke-slate-700"><path d="M1.75 1.75 4 4.25l2.25-2.5" fill="none" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></svg>
            </button>

            <div id="nav-popup" data-reveal-target="item" data-turbo-temporary="true" class="hidden">
              <div data-action="click->reveal#hide" class="fixed inset-0 z-[25] height-screen w-screen bg-slate-800/40 backdrop-blur-sm opacity-100" aria-hidden="true"></div>
              <div class="fixed inset-x-4 top-8 z-[50] origin-top rounded-3xl bg-white p-8 ring-1 ring-slate-900/5 opacity-100 scale-100" tabindex="-1">
                <div class="flex flex-row-reverse items-center justify-between">
                  <button data-action="click->reveal#hide" aria-label="Close menu" class="-m-1 p-1" type="button" tabindex="0">
                    <svg viewBox="0 0 24 24" aria-hidden="true" class="h-6 w-6 text-slate-500"><path d="m17.25 6.75-10.5 10.5M6.75 6.75l10.5 10.5" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></svg>
                  </button>

                  <h2 class="text-sm font-medium text-slate-600">Navigation</h2>
                </div>

                <nav class="mt-6">
                  <ul class="-my-2 divide-y divide-slate-100 text-base text-slate-800">
                    <li>
                      <%= link_to about_path, class: "block py-2 transition link-primary font-bold" do %>
                        <span aria-hidden="true" class="select-none">🧑‍💻 </span>About
                      <% end %>
                    </li>
                    <li>
                      <%= link_to posts_path, class: "block py-2 transition link-primary font-bold" do %>
                        <span aria-hidden="true" class="select-none">🗃️ </span>All Posts
                      <% end %>
                    </li>
                    <li>
                      <%= link_to articles_path, class: "block py-2 transition link-primary font-bold" do %>
                        <span aria-hidden="true" class="select-none">📝 </span>Articles
                      <% end %>
                    </li>
                    <li>
                      <%= link_to notes_path, class: "block py-2 transition link-primary font-bold" do %>
                        <span aria-hidden="true" class="select-none">✏️ </span>Notes
                      <% end %>
                    </li>
                    <li>
                      <%= link_to photos_path, class: "block py-2 transition link-primary font-bold" do %>
                        <span aria-hidden="true">📷 Photos
                      <% end %>
                    </li>
                    <li>
                      <%= link_to check_ins_path, class: "block py-2 transition link-primary font-bold" do %>
                        <span aria-hidden="true" class="select-none">📍 </span>Check-Ins
                      <% end %>
                    </li>
                    <li>
                      <%= link_to links_path, class: "block py-2 transition link-primary font-bold" do %>
                        <span aria-hidden="true" class="select-none">🔗 </span>Links
                      <% end %>
                    </li>
                    <li>
                      <form id="search" class="mt-2 relative max-w-sm" data-controller="search" data-action="search#submit:prevent">
                        <div class="pointer-events-none absolute inset-y-0 left-0 flex items-center">
                          <span aria-hidden="true" class="text-center h-6 w-6 ml-1 pl-1">🔎</span>
                        </div>

                        <input type="text" data-action="input->search#toggleClear" data-search-target="query" value="<%= params[:q] %>" class="w-full pl-8 pr-7 border border-slate-300 rounded-md shadow-sm focus:ring-pink-500 focus:border-pink-500 block sm:text-sm" placeholder="Search my posts!" aria-label="Search" />

                        <div class="absolute inset-y-0 right-0 flex items-center">
                          <button type="button" data-search-target="clear" data-action="search#clear" class="h-6 w-6 mr-1<%= " hidden" unless params[:q] %>" title="Clear search" aria-label="Clear search">
                            ❌
                          </button>
                        </div>

                        <input type="submit" class="hidden" />
                      </form>
                    </li>
                  </ul>
                </nav>
              </div>
            </div>
          </div>

          <nav class="hidden lg:block">
            <ul class="flex rounded-full bg-white/90 px-3 text-sm font-medium text-slate-800 shadow-lg shadow-slate-800/5 ring-1 ring-slate-900/5 backdrop-blur">
              <li><%= link_to "About", about_path, class: "relative block px-3 py-2 transition link-primary font-bold" %></li>
              <li><%= link_to "All Posts", posts_path, class: "relative block px-3 py-2 transition link-primary font-bold" %></li>
              <li><%= link_to "Articles", articles_path, class: "relative block px-3 py-2 transition link-primary font-bold" %></li>
              <li><%= link_to "Notes", notes_path, class: "relative block px-3 py-2 transition link-primary font-bold" %></li>
              <li><%= link_to "Photos", photos_path, class: "relative block px-3 py-2 transition link-primary font-bold" %></li>
              <li><%= link_to "Check-Ins", check_ins_path, class: "relative block px-3 py-2 transition link-primary font-bold" %></li>
              <li><%= link_to "Links", links_path, class: "relative block px-3 py-2 transition link-primary font-bold" %></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_waveform.html.erb
<svg id="waveform" data-turbo-permanent="true" aria-hidden="true" class="absolute left-0 top-0 h-20 w-full">
  <defs>
    <linearGradient id=":r0:-fade" x1="0" x2="0" y1="0" y2="1">
      <stop offset="40%" stop-color="white"></stop>
      <stop offset="100%" stop-color="black"></stop>
    </linearGradient>
    <linearGradient id=":r0:-gradient">
      <stop offset="0%" stop-color="#4989E8"></stop>
      <stop offset="50%" stop-color="#6159DA"></stop>
      <stop offset="100%" stop-color="#FF54AD"></stop>
    </linearGradient>
    <mask id=":r0:-mask"><rect width="100%" height="100%" fill="url(#:r0:-pattern)"></rect></mask>
    <pattern id=":r0:-pattern" width="400" height="100%" patternUnits="userSpaceOnUse">
      <% Array.new(100) { rand(40..100) }.each_with_index do |height, index| %>
        <rect key="<%= index %>" width="2" height="<%= height %>%" x="<%= 2 * (index + 1) + 2 * index %>" fill="url(#:r0:-fade)"></rect>
      <% end %>
    </pattern>
  </defs>
  <rect width="100%" height="100%" fill="url(#:r0:-gradient)" mask="url(#:r0:-mask)" opacity="0.25"></rect>
</svg>

app/views/application/_work.html.erb
<ol class="mt-6 space-y-4">
  <% Resume::Job.first(5).each do |job| %>
    <li class="flex gap-4">
      <div class="select-none relative flex h-10 w-10 flex-none items-center justify-center rounded-full shadow-md shadow-slate-800/5 ring-1 ring-slate-900/5">
        <%= image_tag job.image, width: 28, height: 28, class: "h-7 w-7", loading: "lazy", style: "color: transparent;", decoding: "async", data: {nimg: 1} %>
      </div>

      <dl class="flex flex-auto flex-wrap gap-x-2">
        <dt class="sr-only select-none">Company</dt>
        <dd class="w-full flex-none text-sm font-medium text-slate-900"><%= job.name %></dd>
        <dt class="sr-only select-none">Role</dt>
        <dd class="text-xs text-slate-500"><%= job.position %></dd>
        <dt class="sr-only select-none">Date</dt>
        <dd class="ml-auto text-xs text-slate-400" aria-label="July 2021 until Now">
          <time datetime="<%= job.start_date.strftime("%Y-%m-%d") %>"><%= job.start_date.year %></time> <span aria-hidden="true">—</span> <time datetime="<%= (job.end_date || Date.today).strftime("%Y-%m-%d") %>"><%= job.end_date&.year || "Now" %></time>
        </dd>
      </dl>
    </li>
  <% end %>
</ol>

<%= link_to asset_path("cv.pdf", skip_pipeline: true), class: "inline-flex items-center gap-2 justify-center rounded-md py-2 px-3 text-sm outline-offset-2 transition active:transition-none bg-slate-100 font-medium hover:bg-pink-100 active:bg-slate-100 active:text-pink-900/60 link-primary group mt-6 w-full" do %>
  Download CV<svg viewBox="0 0 16 16" fill="none" aria-hidden="true" class="h-4 w-4 stroke-pink-500 group-hover:stroke-pink-700 transition group-active:stroke-pink-900"><path d="M4.75 8.75 8 12.25m0 0 3.25-3.5M8 12.25v-8.5" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></svg>
<% end %>