config/routes.rb
require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  root to: "posts#index"

  get "/about", to: "pages#about"
  get "/pdx-food", to: "pages#pdx_food"

  # For the generic /posts/:id route (i.e. to route to a post without using
  # its type, like Article or Note), we'll only support numeric IDs. Only
  # polymorphic routes will support something like fetching posts by slugs.
  # This also ensures that our legacy URLs listed below won't conflict.
  get "/posts/:id", to: "posts#show", as: :post, constraints: {id: /\d+/}

  resources :posts, only: [:index, :create, :edit, :update, :destroy]
  resources :articles, only: [:index, :show]
  resources :check_ins, only: [:index, :show], path: "check-ins"
  resources :links, only: [:index, :show]
  resources :notes, only: [:index, :show]
  resources :photos, only: [:index]
  resources :hashtags, only: [:show]

  resources :feeds, only: [:index]
  get "/rss", to: "feeds#index"

  get "/feeds/all", to: "feeds#all", format: :xml, as: :all_feed
  get "/feeds/articles", to: "feeds#articles", format: :xml, as: :articles_feed
  get "/feeds/check-ins", to: "feeds#check_ins", format: :xml, as: :check_ins_feed
  get "/feeds/links", to: "feeds#links", format: :xml, as: :links_feed
  get "/feeds/notes", to: "feeds#notes", format: :xml, as: :notes_feed
  get "/feeds/photos", to: "feeds#photos", format: :xml, as: :photos_feed
  get "/feeds/main", to: "feeds#main", format: :xml, as: :main_feed
  get "/feed", to: "feeds#main", format: :xml

  post :webmention, to: "webmentions#receive"

  # Set up routes for me to authenticate and write/edit posts.
  namespace :github do
    namespace :oauth do
      get :callback
    end
  end

  # Route media attachments through a CDN.
  direct :cdn_file do |file|
    if Rails.configuration.cdn_host.present?
      File.join(Rails.configuration.cdn_host, file.key)
    else
      route_for(:rails_blob, file)
    end
  end

  post :direct_uploads, to: "direct_uploads#create", as: :direct_uploads

  constraints(AdminConstraint.new) do
    mount Sidekiq::Web => "/admin/sidekiq"
  end

  get :sign_in, to: "sessions#new"
  delete :sign_out, to: "sessions#destroy"
  get "/mapkit/token", to: "sessions#mapkit_token"

  # Finally, ensure old URLs redirect to the new location for existing articles
  get "/blog/2012/02/01/why-i-hate-five-star-ratings", to: redirect("/articles/why-i-hate-five-star-ratings/")
  get "/blog/2012/02/07/collaborative-filtering-with-likes-and-dislikes", to: redirect("/articles/collaborative-filtering-with-likes-and-dislikes/")
  get "/blog/2012/07/18/the-current-state-of-rails-inflections", to: redirect("/articles/the-state-of-rails-inflections/")
  get "/blog/2012/07/31/edge-rails-a-multilingual-inflector", to: redirect("/articles/internationalization-and-the-rails-inflector/")
  get "/blog/2012/09/06/stop-validating-email-addresses-with-regex", to: redirect("/articles/stop-validating-email-addresses-with-regex/")
  get "/blog/2013/03/20/the-story-of-my-redis-database", to: redirect("/articles/from-1-5-gb-to-50-mb-the-story-of-my-redis-database/")
  get "/blog/2013/05/02/deploying-discourse-with-capistrano", to: redirect("/articles/deploying-discourse-with-capistrano/")
  get "/blog/2015/01/29/distance-constraints-with-postgresql-and-postgis", to: redirect("/articles/distance-constraints-with-postgresql-and-postgis/")

  get "/posts/why-i-hate-five-star-ratings", to: redirect("/articles/why-i-hate-five-star-ratings/")
  get "/posts/collaborative-filtering-with-likes-and-dislikes", to: redirect("/articles/collaborative-filtering-with-likes-and-dislikes/")
  get "/posts/the-current-state-of-rails-inflections", to: redirect("/articles/the-state-of-rails-inflections/")
  get "/posts/edge-rails-a-multilingual-inflector", to: redirect("/articles/internationalization-and-the-rails-inflector/")
  get "/posts/stop-validating-email-addresses-with-regex", to: redirect("/articles/stop-validating-email-addresses-with-regex/")
  get "/posts/the-story-of-my-redis-database", to: redirect("/articles/from-1-5-gb-to-50-mb-debugging-memory-usage-in-redis/")
  get "/posts/deploying-discourse-with-capistrano", to: redirect("/articles/deploying-discourse-with-capistrano/")
  get "/posts/distance-constraints-with-postgresql-and-postgis", to: redirect("/articles/distance-constraints-with-postgresql-and-postgis/")
  get "/posts/publish-your-site-to-s3", to: redirect("/articles/easily-publish-your-site-to-s3-and-cloudfront/")
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || content_for(:og_title) || "@davidcelis" %></title>

    <meta name="description" content="<%= content_for(:og_description) || "Lukewarm takes from an amateur pizzaiolo and software engineer." %>">

    <%= auto_discovery_link_tag(:atom, main_feed_url, title: "davidcel.is") %>
    <%= auto_discovery_link_tag(:atom, articles_feed_url, title: "davidcel.is - Articles") %>
    <%= auto_discovery_link_tag(:atom, check_ins_feed_url, title: "davidcel.is - Check-ins") %>
    <%= auto_discovery_link_tag(:atom, links_feed_url, title: "davidcel.is - Links") %>
    <%= auto_discovery_link_tag(:atom, notes_feed_url, title: "davidcel.is - Notes") %>
    <%= auto_discovery_link_tag(:atom, photos_feed_url, title: "davidcel.is - Photos") %>
    <%= auto_discovery_link_tag(:atom, all_feed_url, title: "davidcel.is - All Posts") %>

    <link rel="webmention" href="<%= webmention_url %>" />

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://cdn.fontshare.com" crossOrigin="anonymous"/>
    <link rel="stylesheet" href="https://api.fontshare.com/v2/css?f[]=satoshi@700,500,400&display=swap"/>

    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "prism", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "prism", "data-turbo-track": "reload" %>

    <link href="https://cdn.jsdelivr.net/npm/lightgallery@2.7.1/css/lightgallery-bundle.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tippy.js@6.3.7/dist/tippy.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/tippy.js@6.3.7/themes/light.css" rel="stylesheet">

    <%= javascript_importmap_tags %>

    <link rel="icon" type="image/x-icon" sizes="48x48" href="/favicon.ico">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">

    <%= content_for(:head) %>

    <meta property="og:title" content="<%= content_for(:og_title) || "davidcel.is" %>">
    <meta property="og:description" content="<%= content_for(:og_description) || "Lukewarm takes from an amateur pizzaiolo and software engineer." %>">
    <meta property="og:type" content="<%= content_for(:og_type) || "website" %>">
    <meta property="og:url" content="<%= content_for(:og_url) || request.original_url %>">

    <%= content_for(:og_image) %>
    <%= content_for(:og_video) %>

    <meta name="twitter:card" content="<%= content_for(:twitter_card) || "summary" %>">
    <meta name="twitter:site" content="@davidcelis">
    <meta name="twitter:creator" content="@davidcelis">
    <meta name="twitter:title" content="<%= content_for(:og_title) || "davidcel.is" %>">
    <meta name="twitter:description" content="<%= content_for(:og_description) || "Lukewarm takes from an amateur pizzaiolo and software engineer." %>">
    <%= content_for(:twitter_image) %>

    <% if Rails.env.production? && !authenticated? %>
      <script defer data-domain="davidcel.is" src="https://pls.davidcel.is/js/script.js"></script>
    <% end %>
  </head>

  <body class="bg-white antialiased">
    <%= render "header" %>

    <%= render "flash" %>

    <main class="border-t border-slate-200 lg:relative lg:ml-96 lg:border-t-0 xl:ml-[26rem]">
      <%= render "waveform" %>
      <%= render "navigation" %>

      <div class="relative">
        <%= yield %>
      </div>
    </main>

    <%= render "footer" %>
  </body>
</html>